apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
  name: nri-memory-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
    {{- include "nri-plugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "nri-plugin.labels" . | nindent 8 }}
    spec:
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      nodeSelector:
        kubernetes.io/os: "linux"
    {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.nri.runtime.patchConfig }}
      initContainers:
      - name: patch-runtime
        {{- if (not (or (eq .Values.nri.runtime.config nil) (eq .Values.nri.runtime.config.pluginRegistrationTimeout ""))) }}
        args:
          - -nri-plugin-registration-timeout
          - {{ .Values.nri.runtime.config.pluginRegistrationTimeout }}
          - -nri-plugin-request-timeout
          - {{ .Values.nri.runtime.config.pluginRequestTimeout }}
        {{- end }}
        image: {{ .Values.initContainerImage.name }}:{{ .Values.initContainerImage.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.initContainerImage.pullPolicy }}
        volumeMounts:
        - name: containerd-config
          mountPath: /etc/containerd
        - name: crio-config
          mountPath: /etc/crio/crio.conf.d
        - name: dbus-socket
          mountPath: /var/run/dbus/system_bus_socket
        securityContext:
          privileged: true
      {{- end }}
      containers:
        - name: nri-memory-policy
          command:
            - nri-memory-policy
            - --idx
            - "{{ .Values.nri.plugin.index | int | printf "%02d"  }}"
            - --config
            - /etc/nri/memory-policy/config.yaml
            - -v
          image: {{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
          volumeMounts:
          - name: memory-policy-config-vol
            mountPath: /etc/nri/memory-policy
          - name: nrisockets
            mountPath: /var/run/nri
          - name: mpolset-vol
            mountPath: /mnt/nri-memory-policy-mpolset
      {{- if .Values.podPriorityClassNodeCritical }}
      priorityClassName: system-node-critical
      {{- end }}
      volumes:
      - name: memory-policy-config-vol
        configMap:
          name: nri-memory-policy-config.default
      - name: nrisockets
        hostPath:
          path: /var/run/nri
          type: DirectoryOrCreate
      - name: mpolset-vol
        hostPath:
          path: /mnt/nri-memory-policy-mpolset
          type: DirectoryOrCreate
      {{- if .Values.nri.runtime.patchConfig }}
      - name: containerd-config
        hostPath:
          path: /etc/containerd/
          type: DirectoryOrCreate
      - name: crio-config
        hostPath:
          path: /etc/crio/crio.conf.d/
          type: DirectoryOrCreate
      - name: dbus-socket
        hostPath:
          path: /var/run/dbus/system_bus_socket
          type: Socket
      {{- end }}
