#!/bin/bash

hook="${0##*/}"
dotd="${0}.d"
orig="${0%/*}/../.git/hooks/$hook"

exec 1>&2

for h in "$dotd"/???*; do
    case "$h" in
        *~|*.swp)
            continue
            ;;
        [0-9]*-*)
            ;;
        *)
            continue
            ;;
    esac
    if [ ! -x "$h" ]; then
        continue
    fi

    echo "[running git hook ${h##*/}]"
    $h $@
    status=$?
    if [ $status != 0 ]; then
        exit $status
    fi
done

if [ -x "$orig" ]; then
    exec $orig
fi
