apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nri-resource-policy
  name: nri-resource-policy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nri-resource-policy
  template:
    metadata:
      labels:
        app: nri-resource-policy
    spec:
      serviceAccount: nri-resource-policy
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        - name: nri-resource-policy-topology-aware
          args:
            - --host-root
            - /host
            - --fallback-config
            - /etc/nri-resource-policy/nri-resource-policy.cfg
            - --pid-file
            - /tmp/nri-resource-policy.pid
            - -metrics-interval
            - 5s
          ports:
            - containerPort: 8891
              name: metrics
              protocol: TCP
              hostPort: 8891
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
          - name: resource-policydata
            mountPath: /var/lib/nri-resource-policy
          - name: hostsysfs
            mountPath: /host/sys
          - name: resource-policysockets
            mountPath: /var/run/nri-resource-policy
          - name: resource-policyconfig
            mountPath: /etc/nri-resource-policy
          - name: nrisockets
            mountPath: /var/run/nri
      volumes:
      - name: resource-policydata
        hostPath:
          path: /var/lib/nri-resource-policy
          type: DirectoryOrCreate
      - name: hostsysfs
        hostPath:
          path: /sys
          type: Directory
      - name: resource-policysockets
        hostPath:
          path: /var/run/nri-resource-policy
      - name: resource-policyconfig
        configMap:
          name: nri-resource-policy-config.default
      - name: nrisockets
        hostPath:
          path: /var/run/nri
          type: Directory
