//go:build !ignore_autogenerated

// Copyright The NRI Plugins Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package policy

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingClass) DeepCopyInto(out *SchedulingClass) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make(SchedulingFlags, len(*in))
		copy(*out, *in)
	}
	if in.Nice != nil {
		in, out := &in.Nice, &out.Nice
		*out = new(int)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(uint64)
		**out = **in
	}
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = new(uint64)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(uint64)
		**out = **in
	}
	if in.IOPriority != nil {
		in, out := &in.IOPriority, &out.IOPriority
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingClass.
func (in *SchedulingClass) DeepCopy() *SchedulingClass {
	if in == nil {
		return nil
	}
	out := new(SchedulingClass)
	in.DeepCopyInto(out)
	return out
}
