apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-resource-policy-balloons-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "balloons-plugin.labels" . | nindent 4 }}
data:
  policy: |+
    {{- toYaml .Values.config | nindent 4 }}
