apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "balloons-plugin.labels" . | nindent 4 }}
  name: nri-resource-policy-balloons
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
    {{- include "balloons-plugin.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "balloons-plugin.labels" . | nindent 8 }}
    spec:
      serviceAccount: nri-resource-policy-balloons
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        - name: nri-resource-policy-balloons
          args:
            - --host-root
            - /host
            - --fallback-config
            - /etc/nri-resource-policy/nri-resource-policy.cfg
            - --pid-file
            - /tmp/nri-resource-policy.pid
            - -metrics-interval
            - 5s
          ports:
            - containerPort: 8891
              protocol: TCP
              hostPort: {{ .Values.hostPort }}
              name: metrics
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: {{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
          volumeMounts:
          - name: resource-policydata
            mountPath: /var/lib/nri-resource-policy
          - name: hostsysfs
            mountPath: /host/sys
          - name: resource-policysockets
            mountPath: /var/run/nri-resource-policy
          - name: resource-policyconfig
            mountPath: /etc/nri-resource-policy
          - name: nrisockets
            mountPath: /var/run/nri
      volumes:
      - name: resource-policydata
        hostPath:
          path: /var/lib/nri-resource-policy
          type: DirectoryOrCreate
      - name: hostsysfs
        hostPath:
          path: /sys
          type: Directory
      - name: resource-policysockets
        hostPath:
          path: /var/run/nri-resource-policy
      - name: resource-policyconfig
        configMap:
          name: nri-resource-policy-config.default
      - name: nrisockets
        hostPath:
          path: /var/run/nri
          type: Directory
