# Default values for nri-plugins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
image:
  name: ghcr.io/containers/nri-plugins/nri-resource-policy-topology-aware
  # tag, if defined will use the given image tag, otherwise Chart.AppVersion will be used
  #tag: unstable
  pullPolicy: Always

config:
  reservedResources:
    cpu: 750m
  control:
    rdt:
      enable: false
      usePodQoSAsDefaultClass: true
      options:
        l2:
          optional: true
        l3:
          optional: true
        mb:
          optional: true
      partitions:
        fullCache:
          l2Allocation:
            all:
              unified: 100%
          l3Allocation:
            all:
              unified: 100%
          classes:
            BestEffort:
              l2Allocation:
                all:
                  unified: 33%
              l3Allocation:
                all:
                  unified: 33%
            Burstable:
              l2Allocation:
                all:
                  unified: 66%
              l3Allocation:
                all:
                  unified: 66%
            Guaranteed:
              l2Allocation:
                all:
                  unified: 100%
              l3Allocation:
                all:
                  unified: 100%
  log:
    source: true
    klog:
      skip_headers: true
    debug:
      - none
  instrumentation:
    httpEndpoint: ":8891"
    prometheusExport: false
    reportPeriod: 60s
    samplingRatePerMillion: 0

# configGroupLabel: config.nri/group

# Extra environment variables to inject.
#extraEnv:
#   VAR1: VAL1
#   VAR2: VAL2

plugin-test:
  enableAPIs: false

resources:
  cpu: 500m
  memory: 512Mi

nri:
  plugin:
    index: 90
    annotations:
#      key1: value1
#      key2: value2
  runtime:
    patchConfig: false
#   config:
#     pluginRegistrationTimeout: 5s
#     pluginRequestTimeout: 2s

initContainerImage:
  name: ghcr.io/containers/nri-plugins/nri-config-manager
  # If not defined Chart.AppVersion will be used
  #tag: unstable
  pullPolicy: Always

tolerations: []
#
# Example:
#
# tolerations:
# - key: "node-role.kubernetes.io/control-plane"
#   operator: "Exists"
#   effect: "NoSchedule"

affinity: []
#
# Example:
#
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: topology.kubernetes.io/disk
#           operator: In
#           values:
#           - ssd

nodeSelector: []
#
# Example:
#
# nodeSelector:
#  kubernetes.io/disk: "ssd"

# NRI plugins should be considered as part of the container runtime.
# By default we make them part of the system-node-critical priority
# class. This should mitigate the potential risk of a plugin getting
# evicted under heavy system load. It should also ensure that during
# autoscaling enough new nodes are brought up to leave room for the
# plugin on each new node.
podPriorityClassNodeCritical: true

# extra ports to expose, and optionally to the host too
#ports: []
#
# Example
#
# ports:
#   - name: lunch
#     container: 61453
#     #host: 61453 # if you want to expose this as a host-port, too
