apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

images:
- name: '*'
  newName: ghcr.io/containers/nri-plugins/nri-resource-policy-balloons
  newTag: unstable

resources:
- ../../base/crds
- ../../base/nri-resource-policy
- sample-configmap.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: nri-resource-policy-balloons
    target:
      group: apps
      version: v1
      kind: DaemonSet
      labelSelector: "app=nri-resource-policy"
    options:
      allowNameChange: true
