apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-resource-policy-config.default
data:
  policy: |+
    ReservedResources:
      cpu: 750m
  #  balloons:
  #    PinCPU: true
  #    PinMemory: true
  #    IdleCPUClass: lowpower
  #    BalloonTypes:
  #      - Name: "quad"
  #        MinCpus: 1
  #        MaxCPUs: 4
  #        CPUClass: dynamic
  #        Namespaces:
  #          - "*"
  #cpu: |+
  #  classes:
  #    lowpower:
  #      minFreq: 800
  #      maxFreq: 800
  #    dynamic:
  #      minFreq: 800
  #      maxFreq: 3600
  #    turbo:
  #      minFreq: 3000
  #      maxFreq: 3600
  #      uncoreMinFreq: 2000
  #      uncoreMaxFreq: 2400
  #instrumentation: |+
  #  # The balloons policy exports containers running in each balloon,
  #  # and cpusets of balloons. Accessible in command line:
  #  # curl --silent http://localhost:8891/metrics
  #  HTTPEndpoint: :8891
  #  PrometheusExport: true
  #logger: |+
  #  Debug: resource-manager,cache,policy,resource-control
