apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-resource-policy-config.default
data:
  nri-resource-policy.cfg: |+
    policy:
      Active: balloons
      AvailableResources:
        CPU: cpuset:0-15
      ReservedResources:
        CPU: 1
      balloons:
        PinCPU: true
        PinMemory: true
        BalloonTypes:
          - Name: btype0
            MinCPUs: 2
            MaxCPUs: 2
            AllocationPriority: 0
            CPUClass: classA
            PreferNewBalloons: true
            PreferSpreadingPods: false
            MinBalloons: 1
          - Name: btype2
            Namespaces:
              - "*"
              - btype2ns1
            MinCPUs: 4
            MaxCPUs: 8
            MinBalloons: 1
            AllocatorPriority: 2
            CPUClass: classB
            PreferNewBalloons: false
            PreferSpreadingPods: false
    instrumentation:
      HTTPEndpoint: :8891
      PrometheusExport: true
    logger:
      Debug: policy,cpu
    cpu:
      classes:
        default:
          minFreq: 800
          maxFreq: 2800
        classA:
          minFreq: 900
          maxFreq: 2900
        classB:
          minFreq: 1000
          maxFreq: 3000
        classC:
          minFreq: 1100
          maxFreq: 3100
          energyPerformancePreference: 1
