apiVersion: v2
appVersion: unstable
description: |
  The template NRI resource policy plugin is a wireframe implementation without any policy logic. It can be used as a template to create new policies.
name: nri-resource-policy-template
sources:
 - https://github.com/containers/nri-plugins
home: https://github.com/containers/nri-plugins
type: application
version: v0.0.0
