# permissions for end users to view nriplugindeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nriplugindeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nri-plugins-operator
    app.kubernetes.io/part-of: nri-plugins-operator
    app.kubernetes.io/managed-by: kustomize
  name: nriplugindeployment-viewer-role
rules:
- apiGroups:
  - config.nri
  resources:
  - nriplugindeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.nri
  resources:
  - nriplugindeployments/status
  verbs:
  - get
