apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nri-resource-policy-template
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nri-resource-policy-template
subjects:
- kind: ServiceAccount
  name: nri-resource-policy-template
  namespace: {{ .Release.Namespace }}
