{{- if .Values.config.dra.enabled }}
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: template.nri.io
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
spec:
  selectors:
    - cel:
        expression: device.driver == "template.nri.io"
{{- end }}
