apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nri-resource-policy-topology-aware
  labels:
    {{- include "topology-aware-plugin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
- apiGroups:
  - topology.node.k8s.io
  resources:
  - noderesourcetopologies
  verbs:
  - create
  - get
  - list
  - update
  - delete
