apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-resource-policy-topology-aware
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topology-aware-plugin.labels" . | nindent 4 }}
