name: Verify

on:
  push:
    branches:
      - main
      - "release-*"
      - "test/**"
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  verify-deps:
    name: Dependencies
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          make verify-godeps

  verify-formatting:
    name: Formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          if ! git diff-index --check origin/${{ github.base_ref }} --; then
              echo "This PR would introduce the errors shown above."
              echo "Please fix them and update the PR."
              exit 1
          fi
        if: ${{ github.event_name == 'pull_request' }}
      - run: |
          make verify-fmt

  verify-generated:
    name: Generated Assets
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          make verify-generate

  verify-build:
    name: Builds
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          make verify-build

  verify-docs:
    name: Documentation
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          pip3 install --user -r docs/requirements.txt
          echo "`python3 -m site --user-base`/bin" >> $GITHUB_PATH
      - run: |
          git config user.name "Github"
          git config user.email "no-reply@github.com"
          ./scripts/build/update-gh-pages.sh

  verify-licenses:
    name: Verify Licenses
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          make install-go-licenses verify-licenses
